services:
  frankenphp:
    build:
      context: ./php
    ports:
      - "80:80"       # HTTP
      - "443:443"     # HTTPS 
      - "443:443/udp" # HTTP/3
    volumes:
      - ./app:/app    
      - ./Caddyfile:/etc/frankenphp/Caddyfile
    environment:
      - APP_NAME=myapp
      - APP_ENV=local
      - APP_KEY=
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=mydb
      - DB_USERNAME=root
      - DB_PASSWORD=secret_password
    depends_on:
      - db

  db:
    image: mariadb:10.8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: secret_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db

volumes:
  db_data: